[versions]
#plugins
gson = "2.13.2"
kotlin = "2.2.21"
agp = "8.13.1"

#libraries
core = "1.7.0"
coreTesting = "2.2.0"
core-ktx = "1.17.0"
appcompat = "1.7.1"
androidLogger = "2.1.6"
kotlinxCoroutinesTest = "1.10.2"
lifecycleExtensions = "2.2.0"
material = "1.13.0"


constraintlayout = "2.2.1"
junit = "4.13.2"
junitExt = "1.3.0"
espressoCore = "3.7.0"
lifecycleKtx = "2.10.0"
mockitoCore = "5.20.0"
mockitoInline = "5.2.0"
mockitoKotlin = "6.1.0"
preferenceKtx = "1.2.1"
robolectric = "4.16"

junitKtx = "1.3.0"

[libraries]
android-logger = { module = "com.github.toyota-m2k:android-logger", version.ref = "androidLogger" }
core = { module = "androidx.test:core", version.ref = "core" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
core-testing = { module = "androidx.arch.core:core-testing", version.ref = "coreTesting" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }
lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycleExtensions" }
material = { module = "com.google.android.material:material", version.ref = "material" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
junit = { module = "junit:junit", version.ref = "junit" }
junitExt = { module = "androidx.test.ext:junit", version.ref = "junitExt" }
espressoCore = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
lifecycleRuntimeKtx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleKtx" }
lifecycleLivedataKtx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleKtx" }
lifecycleViewmodelKtx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleKtx" }
lifecycleService = { module = "androidx.lifecycle:lifecycle-service", version.ref = "lifecycleKtx" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }
mockito-inline = { module = "org.mockito:mockito-inline", version.ref = "mockitoInline" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoKotlin" }
preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
androidx-junit-ktx = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "junitKtx" }

[plugins]
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
